// flow-typed signature: c04dfae5cb8e300ed1c3e6285365a9e5
// flow-typed version: <<STUB>>/belle_v^3.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'belle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'belle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'belle/lib/__tests__/Button-test' {
  declare module.exports: any;
}

declare module 'belle/lib/__tests__/Card-test' {
  declare module.exports: any;
}

declare module 'belle/lib/__tests__/ComboBox-test' {
  declare module.exports: any;
}

declare module 'belle/lib/__tests__/helpers-test' {
  declare module.exports: any;
}

declare module 'belle/lib/__tests__/Option-test' {
  declare module.exports: any;
}

declare module 'belle/lib/__tests__/Placeholder-test' {
  declare module.exports: any;
}

declare module 'belle/lib/__tests__/Rating-test' {
  declare module.exports: any;
}

declare module 'belle/lib/__tests__/Select-test' {
  declare module.exports: any;
}

declare module 'belle/lib/__tests__/Separator-test' {
  declare module.exports: any;
}

declare module 'belle/lib/__tests__/TextInput-test' {
  declare module.exports: any;
}

declare module 'belle/lib/__tests__/union-class-names-test' {
  declare module.exports: any;
}

declare module 'belle/lib/components/ActionArea' {
  declare module.exports: any;
}

declare module 'belle/lib/components/ActionArea/index' {
  declare module.exports: any;
}

declare module 'belle/lib/components/ActionArea/styles' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Button' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Button/config' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Button/index' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Button/styles' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Card' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Card/index' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Choice' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Choice/index' {
  declare module.exports: any;
}

declare module 'belle/lib/components/ComboBox' {
  declare module.exports: any;
}

declare module 'belle/lib/components/ComboBox/ComboBoxItem' {
  declare module.exports: any;
}

declare module 'belle/lib/components/ComboBox/index' {
  declare module.exports: any;
}

declare module 'belle/lib/components/ComboBox/styles' {
  declare module.exports: any;
}

declare module 'belle/lib/components/ComboBoxItem' {
  declare module.exports: any;
}

declare module 'belle/lib/components/DatePicker' {
  declare module.exports: any;
}

declare module 'belle/lib/components/DatePicker/config' {
  declare module.exports: any;
}

declare module 'belle/lib/components/DatePicker/Day' {
  declare module.exports: any;
}

declare module 'belle/lib/components/DatePicker/DisabledDay' {
  declare module.exports: any;
}

declare module 'belle/lib/components/DatePicker/index' {
  declare module.exports: any;
}

declare module 'belle/lib/components/DatePicker/styles' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Day' {
  declare module.exports: any;
}

declare module 'belle/lib/components/DisabledDay' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Option' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Option/index' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Option/styles' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Placeholder' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Placeholder/index' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Placeholder/styles' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Rating' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Rating/config' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Rating/index' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Rating/styles' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Select' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Select/config' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Select/index' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Select/SelectItem' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Select/styles' {
  declare module.exports: any;
}

declare module 'belle/lib/components/SelectItem' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Separator' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Separator/index' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Separator/styles' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Spinner' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Spinner/index' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Spinner/styles' {
  declare module.exports: any;
}

declare module 'belle/lib/components/TextInput' {
  declare module.exports: any;
}

declare module 'belle/lib/components/TextInput/index' {
  declare module.exports: any;
}

declare module 'belle/lib/components/TextInput/styles' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Toggle' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Toggle/config' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Toggle/index' {
  declare module.exports: any;
}

declare module 'belle/lib/components/Toggle/styles' {
  declare module.exports: any;
}

declare module 'belle/lib/config/button' {
  declare module.exports: any;
}

declare module 'belle/lib/config/datePicker' {
  declare module.exports: any;
}

declare module 'belle/lib/config/i18n' {
  declare module.exports: any;
}

declare module 'belle/lib/config/rating' {
  declare module.exports: any;
}

declare module 'belle/lib/config/select' {
  declare module.exports: any;
}

declare module 'belle/lib/config/toggle' {
  declare module.exports: any;
}

declare module 'belle/lib/index' {
  declare module.exports: any;
}

declare module 'belle/lib/style/actionArea' {
  declare module.exports: any;
}

declare module 'belle/lib/style/animations' {
  declare module.exports: any;
}

declare module 'belle/lib/style/button' {
  declare module.exports: any;
}

declare module 'belle/lib/style/card' {
  declare module.exports: any;
}

declare module 'belle/lib/style/combo-box' {
  declare module.exports: any;
}

declare module 'belle/lib/style/date-picker' {
  declare module.exports: any;
}

declare module 'belle/lib/style/option' {
  declare module.exports: any;
}

declare module 'belle/lib/style/placeholder' {
  declare module.exports: any;
}

declare module 'belle/lib/style/rating' {
  declare module.exports: any;
}

declare module 'belle/lib/style/select' {
  declare module.exports: any;
}

declare module 'belle/lib/style/separator' {
  declare module.exports: any;
}

declare module 'belle/lib/style/spinner' {
  declare module.exports: any;
}

declare module 'belle/lib/style/text-input' {
  declare module.exports: any;
}

declare module 'belle/lib/style/toggle' {
  declare module.exports: any;
}

declare module 'belle/lib/utils/animation-frame-management' {
  declare module.exports: any;
}

declare module 'belle/lib/utils/animations' {
  declare module.exports: any;
}

declare module 'belle/lib/utils/calculate-textarea-height' {
  declare module.exports: any;
}

declare module 'belle/lib/utils/createComponent' {
  declare module.exports: any;
}

declare module 'belle/lib/utils/date-helpers' {
  declare module.exports: any;
}

declare module 'belle/lib/utils/helpers' {
  declare module.exports: any;
}

declare module 'belle/lib/utils/inject-style' {
  declare module.exports: any;
}

declare module 'belle/lib/utils/is-component-of-type' {
  declare module.exports: any;
}

declare module 'belle/lib/utils/union-class-names' {
  declare module.exports: any;
}

// Filename aliases
declare module 'belle/lib/__tests__/Button-test.js' {
  declare module.exports: $Exports<'belle/lib/__tests__/Button-test'>;
}
declare module 'belle/lib/__tests__/Card-test.js' {
  declare module.exports: $Exports<'belle/lib/__tests__/Card-test'>;
}
declare module 'belle/lib/__tests__/ComboBox-test.js' {
  declare module.exports: $Exports<'belle/lib/__tests__/ComboBox-test'>;
}
declare module 'belle/lib/__tests__/helpers-test.js' {
  declare module.exports: $Exports<'belle/lib/__tests__/helpers-test'>;
}
declare module 'belle/lib/__tests__/Option-test.js' {
  declare module.exports: $Exports<'belle/lib/__tests__/Option-test'>;
}
declare module 'belle/lib/__tests__/Placeholder-test.js' {
  declare module.exports: $Exports<'belle/lib/__tests__/Placeholder-test'>;
}
declare module 'belle/lib/__tests__/Rating-test.js' {
  declare module.exports: $Exports<'belle/lib/__tests__/Rating-test'>;
}
declare module 'belle/lib/__tests__/Select-test.js' {
  declare module.exports: $Exports<'belle/lib/__tests__/Select-test'>;
}
declare module 'belle/lib/__tests__/Separator-test.js' {
  declare module.exports: $Exports<'belle/lib/__tests__/Separator-test'>;
}
declare module 'belle/lib/__tests__/TextInput-test.js' {
  declare module.exports: $Exports<'belle/lib/__tests__/TextInput-test'>;
}
declare module 'belle/lib/__tests__/union-class-names-test.js' {
  declare module.exports: $Exports<'belle/lib/__tests__/union-class-names-test'>;
}
declare module 'belle/lib/components/ActionArea.js' {
  declare module.exports: $Exports<'belle/lib/components/ActionArea'>;
}
declare module 'belle/lib/components/ActionArea/index.js' {
  declare module.exports: $Exports<'belle/lib/components/ActionArea/index'>;
}
declare module 'belle/lib/components/ActionArea/styles.js' {
  declare module.exports: $Exports<'belle/lib/components/ActionArea/styles'>;
}
declare module 'belle/lib/components/Button.js' {
  declare module.exports: $Exports<'belle/lib/components/Button'>;
}
declare module 'belle/lib/components/Button/config.js' {
  declare module.exports: $Exports<'belle/lib/components/Button/config'>;
}
declare module 'belle/lib/components/Button/index.js' {
  declare module.exports: $Exports<'belle/lib/components/Button/index'>;
}
declare module 'belle/lib/components/Button/styles.js' {
  declare module.exports: $Exports<'belle/lib/components/Button/styles'>;
}
declare module 'belle/lib/components/Card.js' {
  declare module.exports: $Exports<'belle/lib/components/Card'>;
}
declare module 'belle/lib/components/Card/index.js' {
  declare module.exports: $Exports<'belle/lib/components/Card/index'>;
}
declare module 'belle/lib/components/Choice.js' {
  declare module.exports: $Exports<'belle/lib/components/Choice'>;
}
declare module 'belle/lib/components/Choice/index.js' {
  declare module.exports: $Exports<'belle/lib/components/Choice/index'>;
}
declare module 'belle/lib/components/ComboBox.js' {
  declare module.exports: $Exports<'belle/lib/components/ComboBox'>;
}
declare module 'belle/lib/components/ComboBox/ComboBoxItem.js' {
  declare module.exports: $Exports<'belle/lib/components/ComboBox/ComboBoxItem'>;
}
declare module 'belle/lib/components/ComboBox/index.js' {
  declare module.exports: $Exports<'belle/lib/components/ComboBox/index'>;
}
declare module 'belle/lib/components/ComboBox/styles.js' {
  declare module.exports: $Exports<'belle/lib/components/ComboBox/styles'>;
}
declare module 'belle/lib/components/ComboBoxItem.js' {
  declare module.exports: $Exports<'belle/lib/components/ComboBoxItem'>;
}
declare module 'belle/lib/components/DatePicker.js' {
  declare module.exports: $Exports<'belle/lib/components/DatePicker'>;
}
declare module 'belle/lib/components/DatePicker/config.js' {
  declare module.exports: $Exports<'belle/lib/components/DatePicker/config'>;
}
declare module 'belle/lib/components/DatePicker/Day.js' {
  declare module.exports: $Exports<'belle/lib/components/DatePicker/Day'>;
}
declare module 'belle/lib/components/DatePicker/DisabledDay.js' {
  declare module.exports: $Exports<'belle/lib/components/DatePicker/DisabledDay'>;
}
declare module 'belle/lib/components/DatePicker/index.js' {
  declare module.exports: $Exports<'belle/lib/components/DatePicker/index'>;
}
declare module 'belle/lib/components/DatePicker/styles.js' {
  declare module.exports: $Exports<'belle/lib/components/DatePicker/styles'>;
}
declare module 'belle/lib/components/Day.js' {
  declare module.exports: $Exports<'belle/lib/components/Day'>;
}
declare module 'belle/lib/components/DisabledDay.js' {
  declare module.exports: $Exports<'belle/lib/components/DisabledDay'>;
}
declare module 'belle/lib/components/Option.js' {
  declare module.exports: $Exports<'belle/lib/components/Option'>;
}
declare module 'belle/lib/components/Option/index.js' {
  declare module.exports: $Exports<'belle/lib/components/Option/index'>;
}
declare module 'belle/lib/components/Option/styles.js' {
  declare module.exports: $Exports<'belle/lib/components/Option/styles'>;
}
declare module 'belle/lib/components/Placeholder.js' {
  declare module.exports: $Exports<'belle/lib/components/Placeholder'>;
}
declare module 'belle/lib/components/Placeholder/index.js' {
  declare module.exports: $Exports<'belle/lib/components/Placeholder/index'>;
}
declare module 'belle/lib/components/Placeholder/styles.js' {
  declare module.exports: $Exports<'belle/lib/components/Placeholder/styles'>;
}
declare module 'belle/lib/components/Rating.js' {
  declare module.exports: $Exports<'belle/lib/components/Rating'>;
}
declare module 'belle/lib/components/Rating/config.js' {
  declare module.exports: $Exports<'belle/lib/components/Rating/config'>;
}
declare module 'belle/lib/components/Rating/index.js' {
  declare module.exports: $Exports<'belle/lib/components/Rating/index'>;
}
declare module 'belle/lib/components/Rating/styles.js' {
  declare module.exports: $Exports<'belle/lib/components/Rating/styles'>;
}
declare module 'belle/lib/components/Select.js' {
  declare module.exports: $Exports<'belle/lib/components/Select'>;
}
declare module 'belle/lib/components/Select/config.js' {
  declare module.exports: $Exports<'belle/lib/components/Select/config'>;
}
declare module 'belle/lib/components/Select/index.js' {
  declare module.exports: $Exports<'belle/lib/components/Select/index'>;
}
declare module 'belle/lib/components/Select/SelectItem.js' {
  declare module.exports: $Exports<'belle/lib/components/Select/SelectItem'>;
}
declare module 'belle/lib/components/Select/styles.js' {
  declare module.exports: $Exports<'belle/lib/components/Select/styles'>;
}
declare module 'belle/lib/components/SelectItem.js' {
  declare module.exports: $Exports<'belle/lib/components/SelectItem'>;
}
declare module 'belle/lib/components/Separator.js' {
  declare module.exports: $Exports<'belle/lib/components/Separator'>;
}
declare module 'belle/lib/components/Separator/index.js' {
  declare module.exports: $Exports<'belle/lib/components/Separator/index'>;
}
declare module 'belle/lib/components/Separator/styles.js' {
  declare module.exports: $Exports<'belle/lib/components/Separator/styles'>;
}
declare module 'belle/lib/components/Spinner.js' {
  declare module.exports: $Exports<'belle/lib/components/Spinner'>;
}
declare module 'belle/lib/components/Spinner/index.js' {
  declare module.exports: $Exports<'belle/lib/components/Spinner/index'>;
}
declare module 'belle/lib/components/Spinner/styles.js' {
  declare module.exports: $Exports<'belle/lib/components/Spinner/styles'>;
}
declare module 'belle/lib/components/TextInput.js' {
  declare module.exports: $Exports<'belle/lib/components/TextInput'>;
}
declare module 'belle/lib/components/TextInput/index.js' {
  declare module.exports: $Exports<'belle/lib/components/TextInput/index'>;
}
declare module 'belle/lib/components/TextInput/styles.js' {
  declare module.exports: $Exports<'belle/lib/components/TextInput/styles'>;
}
declare module 'belle/lib/components/Toggle.js' {
  declare module.exports: $Exports<'belle/lib/components/Toggle'>;
}
declare module 'belle/lib/components/Toggle/config.js' {
  declare module.exports: $Exports<'belle/lib/components/Toggle/config'>;
}
declare module 'belle/lib/components/Toggle/index.js' {
  declare module.exports: $Exports<'belle/lib/components/Toggle/index'>;
}
declare module 'belle/lib/components/Toggle/styles.js' {
  declare module.exports: $Exports<'belle/lib/components/Toggle/styles'>;
}
declare module 'belle/lib/config/button.js' {
  declare module.exports: $Exports<'belle/lib/config/button'>;
}
declare module 'belle/lib/config/datePicker.js' {
  declare module.exports: $Exports<'belle/lib/config/datePicker'>;
}
declare module 'belle/lib/config/i18n.js' {
  declare module.exports: $Exports<'belle/lib/config/i18n'>;
}
declare module 'belle/lib/config/rating.js' {
  declare module.exports: $Exports<'belle/lib/config/rating'>;
}
declare module 'belle/lib/config/select.js' {
  declare module.exports: $Exports<'belle/lib/config/select'>;
}
declare module 'belle/lib/config/toggle.js' {
  declare module.exports: $Exports<'belle/lib/config/toggle'>;
}
declare module 'belle/lib/index.js' {
  declare module.exports: $Exports<'belle/lib/index'>;
}
declare module 'belle/lib/style/actionArea.js' {
  declare module.exports: $Exports<'belle/lib/style/actionArea'>;
}
declare module 'belle/lib/style/animations.js' {
  declare module.exports: $Exports<'belle/lib/style/animations'>;
}
declare module 'belle/lib/style/button.js' {
  declare module.exports: $Exports<'belle/lib/style/button'>;
}
declare module 'belle/lib/style/card.js' {
  declare module.exports: $Exports<'belle/lib/style/card'>;
}
declare module 'belle/lib/style/combo-box.js' {
  declare module.exports: $Exports<'belle/lib/style/combo-box'>;
}
declare module 'belle/lib/style/date-picker.js' {
  declare module.exports: $Exports<'belle/lib/style/date-picker'>;
}
declare module 'belle/lib/style/option.js' {
  declare module.exports: $Exports<'belle/lib/style/option'>;
}
declare module 'belle/lib/style/placeholder.js' {
  declare module.exports: $Exports<'belle/lib/style/placeholder'>;
}
declare module 'belle/lib/style/rating.js' {
  declare module.exports: $Exports<'belle/lib/style/rating'>;
}
declare module 'belle/lib/style/select.js' {
  declare module.exports: $Exports<'belle/lib/style/select'>;
}
declare module 'belle/lib/style/separator.js' {
  declare module.exports: $Exports<'belle/lib/style/separator'>;
}
declare module 'belle/lib/style/spinner.js' {
  declare module.exports: $Exports<'belle/lib/style/spinner'>;
}
declare module 'belle/lib/style/text-input.js' {
  declare module.exports: $Exports<'belle/lib/style/text-input'>;
}
declare module 'belle/lib/style/toggle.js' {
  declare module.exports: $Exports<'belle/lib/style/toggle'>;
}
declare module 'belle/lib/utils/animation-frame-management.js' {
  declare module.exports: $Exports<'belle/lib/utils/animation-frame-management'>;
}
declare module 'belle/lib/utils/animations.js' {
  declare module.exports: $Exports<'belle/lib/utils/animations'>;
}
declare module 'belle/lib/utils/calculate-textarea-height.js' {
  declare module.exports: $Exports<'belle/lib/utils/calculate-textarea-height'>;
}
declare module 'belle/lib/utils/createComponent.js' {
  declare module.exports: $Exports<'belle/lib/utils/createComponent'>;
}
declare module 'belle/lib/utils/date-helpers.js' {
  declare module.exports: $Exports<'belle/lib/utils/date-helpers'>;
}
declare module 'belle/lib/utils/helpers.js' {
  declare module.exports: $Exports<'belle/lib/utils/helpers'>;
}
declare module 'belle/lib/utils/inject-style.js' {
  declare module.exports: $Exports<'belle/lib/utils/inject-style'>;
}
declare module 'belle/lib/utils/is-component-of-type.js' {
  declare module.exports: $Exports<'belle/lib/utils/is-component-of-type'>;
}
declare module 'belle/lib/utils/union-class-names.js' {
  declare module.exports: $Exports<'belle/lib/utils/union-class-names'>;
}
